### ISSUE TITLE
Health bars disappear until the next stage after exiting `PhotoMode`

### ISSUE THREAD

**Issue by ghost** [6thmoon/HealthBarViewer#1]
https://pastebin.com/T0x86PAx

**Comment by 6thmoon** [comment]
Hey, I was able to figure out exactly what happened by examining the IL instruction addresses in the stack trace. The following code executes when you click the button to enter [*Photo Mode*](https://thunderstore.io/package/Dragonyck/PhotoMode):

```
this.SetIndicatorsVisible(false);
this.OnExit += ( ) => this.SetIndicatorsVisible(true);
```

If the first line throws an exception, then the callback to re-enable indicators (such as health bars) will not fire as it is never assigned. Let's take a look at what happens within this method call:

```
this.cameraRigController.hud.combatHealthBarViewer.enabled = false;
foreach ( PingIndicator ping in PingIndicator.instancesList )
    ping.gameObject.SetActive(false)
```

After disabling the health bar indicators, it attempts to do so for active pings as well. At this point, an `InvalidOperationException` was thrown.

> *Collection was modified; enumeration operation may not execute.* 

The reason this occurs is because `SetActive` indirectly calls `OnDisable`, which updates `PingIndicator.instancesList` during iteration. In fact, any time you attempt to use *Photo Mode* with a ping out, you'll encounter this problem. Issue closed as unrelated to this repository.

Thanks for the report. I appreciate people bringing stuff like this to my attention instead of just ignoring it or complaining elsewhere.

**Comment by 6thmoon** [comment]
```
[Error  : Unity Log] InvalidOperationException: Collection was modified; enumeration operation may not execute.
Stack trace:
System.ThrowHelper.ThrowInvalidOperationException (System.ExceptionResource resource) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_000B)
System.Collections.Generic.List`1[T].ForEach (System.Action`1[T] action) (at <44afb4564e9347cf99a1865351ea8f4a>:IL_0053)
PhotoMode.PhotoModeController.SetIndicatorsVisible (System.Boolean visible) (at <e35e91d0265044f4af687afd40c5b562>:IL_00F3)
PhotoMode.PhotoModeController.EnterPhotoMode (RoR2.UI.PauseScreenController pauseController, RoR2.CameraRigController cameraRigController) (at <e35e91d0265044f4af687afd40c5b562>:IL_0186)
```

**Comment by 6thmoon** [comment]
Updated the original comment. If you know how to get ahold of the author of `PhotoMode` you're welcome to link them this thread. Never used the plugin before so I'm not really interested in pursuing this further.
